# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital
# SPDX-License-Identifier: MIT

name: Setup Node.js
description: Setup the node.js environment

inputs:
  npm-token:
    description: 'The NPM token to use for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm
    - uses: DamianReeves/write-file-action@v1.3
      with:
        path: .npmrc
        contents: |
            @tid-xcut:registry=https://nexus.tid.es/repository/npm-xcut-components/
            //nexus.tid.es/repository/npm-xcut-components/:_auth=${{ inputs.npm-token }}
        write-mode: append
    - name: Install Dependencies
      shell: bash
      run: pnpm i
