# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

rules:
  - name: "Source code"
    headers:
      - files:
          - "**/*.js"
          - "**/*.ts"
          - "src/**"
        license: "Apache-2.0"
        ignore:
          - "*.config.js"
          - "script/**"
  - name: "Templates"
    headers:
      - files:
          - "templates/.github/**/*.yml"
        license:
          - "MIT"
        copyright: "<%= year %> <%= copyrightOwner %>"
        ignore:
          - "templates/.github/ISSUE_TEMPLATE/*.yml"
  - name: "Config files"
    headers:
      - files:
          - ".github/**/*.yml"
          - "**/*.yml"
          - "*.config.js"
        license:
          - "MIT"
          - "Apache-2.0"
  - name: "Scripts"
    headers:
      - files:
          - "script/**"
        license:
          - "MIT"
          - "Apache-2.0"
  - name: "Copyright"
    headers:
      - files:
          - ".github/**/*.yml"
          - "**/*.ts"
          - "**/*.js"
          - "**/*.yml"
        copyright:
          - "\\d{4}(\\s-\\s\\d{4})? Telefónica Innovación Digital and contributors"
          - "\\d{4}(\\s-\\s\\d{4})? Telefónica Innovación Digital"
          - "\\d{4}(\\s-\\s\\d{4})? Telefónica"
ignore:
  - "**/node_modules/**"
  - "dist/**"
  - "dist-action/**"
  - "coverage/**"
  - ".github/ISSUE_TEMPLATE/**"
