# SPDX-FileCopyrightText: 2024 Telef贸nica Innovaci贸n Digital
# SPDX-License-Identifier: MIT

rules:
  - name: "Source code"
    headers:
      - files:
          - "**/*.js"
          - "**/*.ts"
          - "src/**"
        license: "Apache-2.0"
        ignore:
          - "*.config.js"
          - "script/**"
  - name: "Templates"
    headers:
      - files:
          - "templates/.github/**/*.yml"
          - "templates/check-license-compliance-configs/*.yml"
        license:
          - "MIT"
        copyright: "<%= year %> <%= copyrightHolder %>"
        ignore:
          - "templates/.github/ISSUE_TEMPLATE/*.yml"
  - name: "Config files"
    headers:
      - files:
          - ".github/**/*.yml"
          - "**/*.yml"
          - "*.config.js"
        license:
          - "MIT"
          - "Apache-2.0"
  - name: "Scripts"
    headers:
      - files:
          - "script/**"
        license:
          - "MIT"
          - "Apache-2.0"
  - name: "Copyright"
    headers:
      - files:
          - ".github/**/*.yml"
          - "**/*.ts"
          - "**/*.js"
          - "**/*.yml"
        copyright:
          - "\\d{4}(\\s-\\s\\d{4})? Telef贸nica Innovaci贸n Digital( and contributors)?"
    ignore:
      - "templates/.github/**/*.yml"
      - "templates/check-license-compliance-configs/*.yml"
ignore:
  - "**/node_modules/**"
  - "dist/**"
  - "dist-action/**"
  - "coverage/**"
  - ".github/ISSUE_TEMPLATE/**"
