# SPDX-FileCopyrightText: 2024 Telef贸nica Innovaci贸n Digital
# SPDX-License-Identifier: Apache-2.0

name: 'Check Open Source Scaffold'
description: 'GitHub Action to check that the repository is compliant with the open source scaffold'
author: 'Telef贸nica Innovaci贸n Digital'

inputs:
  log:
    description: 'Log level'
    type: choice
    options:
      - 'silly'
      - 'debug'
      - 'verbose'
      - 'info'
      - 'warn'
      - 'error'
      - 'silent'
    default: 'info'
    required: false
  ignore:
    description: 'List of glob patterns to ignore, semi-colon separated'
    required: false
outputs:
  valid:
    description: 'Whether the check passed or not'
  report:
    description: 'A report containing the results of the check'
runs:
  using: node20
  main: dist-action/index.js
