# SPDX-FileCopyrightText: 2024 Telef贸nica Innovaci贸n Digital and contributors
# SPDX-License-Identifier: Apache-2.0

name: 'Check Opensource Scaffold'
description: 'GitHub Action to check that the repository is compliant with the opensource scaffold'
author: 'Telef贸nica Innovaci贸n Digital'

outputs:
  valid:
    description: 'Whether the check passed or not'
  report:
    description: 'A report containing the results of the check'
runs:
  using: node20
  main: dist/index.js
