licenses:
  allowed:
    - Apache-2.0
    - MIT
  warning:
    - BSD
    - LGPL-3.0
    - LGPL-2.0
    - MPL-2.0
    - EPL-1.0
  forbidden:
    - AGPL-3.0
    - GPL-2.0
    - GPL-3.0
errorOnForbidden: true
errorOnWarning: false
# Options passed directly to the license-checker package
licenseCheckerOptions:
  # Global options are applied to all types of checks
  global:
    excludePrivatePackages: true
  # You can also specify options for each type of check. They extend the global options
  # warning:
    # excludePrivatePackages: false
  # forbidden:
    # excludePrivatePackages: false
