# SPDX-FileCopyrightText: 2024 Telefónica and contributors
# SPDX-License-Identifier: MIT

licenses:
  allowed:
    - Apache-2.0
    - MIT
    - BSD-3-Clause
    - BSD-2  -Clause
    - ISC
  warning:
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - LGPL-3.0-only
    - LGPL-3.0-or-later
    - LGPL-3.0
    - LGPL-2.1
    - LGPL-2.0
    - LGPL-3.0+
    - LGPL-2.1+
    - LGPL-2.0+
    - MPL-2.0
    - EPL-1.0
  forbidden:
    - AGPL-3.0-or-later
    - AGPL-3.0-only
    - AGPL-1.0-or-later
    - AGPL-1.0-only
    - GPL-3.0-or-later
    - GPL-3.0-only
    - GPL-2.0-or-later
    - GPL-2.0-only
    - GPL-1.0-or-later
    - GPL-1.0-only
    - AGPL-3.1
    - AGPL-3.0
    - GPL-3.0
    - GPL-2.0
    - GPL-1.0
    - GPL-3.0+
    - GPL-2.0+
    - GPL-1.0+
errorOnForbidden: true
errorOnWarning: false
# Options passed directly to the license-checker package
licenseCheckerOptions:
  # Global options are applied to all types of checks
  global:
    excludePrivatePackages: true
  # You can also specify options for each type of check. They extend the global options
  # warning:
    # excludePrivatePackages: false
  # forbidden:
    # excludePrivatePackages: false
