---
name: Feature Request
description: Suggest an idea to help us improve
title: "[Feature]: "
labels:
  - "feature"
body:
  - type: markdown
    attributes:
      value: >
        **Thanks :heart: for taking the time to fill out this feature request report!** We kindly ask that you search to
        see if an issue [already exists](https://{{ repo_url }}/issues?q=is%3Aissue+sort%3Acreated-desc+) for
        your feature.

        We are also happy to accept contributions from our users. For more details read our [contributing guidelines](https://{{ repo_url }}/blob/master/.github/CONTRIBUTING.md).
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
      value: |
        <!--- Describe your feature here --->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Solution
      description: >
        Describe the solution you'd like. A clear and concise description of what you want to happen. If you have
        considered alternatives, please describe them.
      value: |
        <!--- Describe your solution here --->
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://{{ repo_url }}/blob/master/.github/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
