# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - release
      - feat/cli-generator

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}

      - name: Lint
        run: pnpm lint

      - name: Check spelling
        run: pnpm cspell

      - name: Check TypeScript types
        run: pnpm check:types
      
      - name: Test unit
        run: pnpm test:unit

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Build
        id: build
        run: pnpm build

      - name: Build action
        id: build-action
        run: pnpm action:package

      # This will fail the workflow if the `dist/` directory is different than
      # expected.
      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

      # If `dist/` was different than expected, upload the expected version as a
      # workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  check-opensource-scaffold:
    name: Check Opensource Scaffold
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check Opensource Scaffold
        if: github.event_name != 'pull_request'
        uses: ./

  check-license-compliance:
    name: Check License Compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}

      - name: Check License Compliance
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-license-compliance@v0.1.0

      - name: Check License Compliance
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-license-compliance/.github/actions/check-and-comment@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-spdx-headers:
    name: Check SPDX Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check SPDX Headers
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-spdx-headers@v0.1.0

      - name: Check License Compliance
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-spdx-headers/.github/actions/check-and-comment@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
