# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - release
      - feat/cli-generator

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}

      - name: Lint
        run: npm run lint

      - name: Check spelling
        run: npm run cspell

      - name: Check TypeScript types
        run: npm run check:types
      
      - name: Test unit
        run: npm run test:unit

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Build
        id: build
        run: npm run build

  check-license-compliance:
    name: Check License Compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}

      - name: Check License Compliance
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-license-compliance@v0.1.0

      - name: Check License Compliance
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-license-compliance/.github/actions/check-and-comment@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-spdx-headers:
    name: Check SPDX Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check SPDX Headers
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-spdx-headers@v0.1.0

      - name: Check License Compliance
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-spdx-headers/.github/actions/check-and-comment@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
