# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital
# SPDX-License-Identifier: MIT

name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - release

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node

      - name: Lint
        run: pnpm lint

      - name: Check spelling
        run: pnpm cspell

      - name: Check TypeScript types
        run: pnpm check:types
      
      - name: Test library
        run: pnpm test:library

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Test action
        run: pnpm test:action

      - name: Upload action coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-action
          path: coverage-action/

      - name: Build
        id: build
        run: pnpm build

      # This will fail the workflow if the `dist/` directory is different than
      # expected.
      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

      # If `dist/` was different than expected, upload the expected version as a
      # workflow artifact.
      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        id: upload-dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      # This will fail the workflow if the `dist-action/` directory is different than
      # expected.
      - name: Compare Directories
        id: diff-action
        run: |
          if [ ! -d dist-action/ ]; then
            echo "Expected dist-action/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist-action/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist-action/
            exit 1
          fi

      # If `dist-action/` was different than expected, upload the expected version as a
      # workflow artifact.
      - if: ${{ failure() && steps.diff-action.outcome == 'failure' }}
        name: Upload Artifact
        id: upload-dist-action
        uses: actions/upload-artifact@v4
        with:
          name: dist-action
          path: dist-action/

      
