# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

name: Initialize repository

on:
  workflow_dispatch:
    inputs:
      license:
        type: choice
        description: License to use
        options: 
          - Apache-2.0
          - MPL-2.0
        required: true
      name:
        type: string
        description: Project name
        required: true
      copyright:
        type: string
        description: Copyright owner
        required: true
      description:
        type: string
        description: Project description
        required: false
      email:
        type: string
        description: Community email
        required: false


permissions:
  contents: write
  pull-requests: write
  statuses: write
  actions: write

jobs:
  init-scaffold:
    name: Init scaffold and open PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: foo-token

      - name: Build
        run: pnpm build

      - name: Create scaffold
        run: pnpm opensource-scaffold create --overwrite --no-prompts --log=debug --license=${{ github.event.inputs.license }} --name=${{ github.event.inputs.name }} --copyright=${{ github.event.inputs.copyright }} --description="${{ github.event.inputs.description }}" --repo=${{ github.server_url }}/${{ github.repository }} --email=${{ github.event.inputs.email }}

      - name: Delete scaffold generator resources
        run: |
          rm -rf .github/actions/setup-node
          rm -f .github/workflows/build.yml
          rm -f .github/workflows/init.yml
          rm -f .github/workflows/publish.yml
          rm -rf .husky
          rm -rf .vscode
          rm -rf action
          rm -rf bin
          rm -rf cspell
          rm -rf dist-action
          rm -rf docs
          rm -rf script
          rm -rf src
          rm -rf templates
          rm -rf test
          rm -rf .env.example
          rm -rf .gitattributes
          rm -rf .node-version
          rm -rf .npmrc
          rm -rf action.yml
          rm -rf babel.config.cjs
          rm -rf cspell.config.cjs
          rm -rf eslint.config.js
          rm -rf jest.action.config.cjs
          rm -rf jest.library.config.cjs
          rm -rf package.json
          rm -rf pnpm-lock.yaml
          rm -rf tsconfig.base.json
          rm -rf tsconfig.json

      - name: Move github workflows to avoid requiring workflow permissions
        run: |
          mv .github .github-draft

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          HUSKY: '0'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Initialize repository"
          title: "Initialize opensource project"
          body: |
            This PR initializes the repository with the following configuration:
            
            - License: ${{ github.event.inputs.license }}
            - Name: ${{ github.event.inputs.name }}
            - Copyright: ${{ github.event.inputs.copyright }}
            - Description: ${{ github.event.inputs.description || 'No description provided' }}
            - Email: ${{ github.event.inputs.email || 'No email provided' }}
            - Repository url: ${{ github.server_url }}/${{ github.repository }}

            > [!WARNING]
            > __Before merging the PR, check out the branch and rename the .github-draft folder to .github__. I couldn't do it for you because I don't have the required permissions to create workflows.

            ```bash
            git clone git@github.com:/${{ github.repository }}.git
            cd ${{ github.event.repository.name }}
            git checkout init-repo
            mv .github-draft .github
            git add .
            git commit -m "Enable workflows"
            git push
            ```
          branch: "init-repo"
          base: "test/init-2"
