name: "Check license integrity"
on:
  pull_request:

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Check license headers
        # cspell:disable-next-line
        uses: viperproject/check-license-header@v2
        with:
          path: .
          config: ./.github/license-headers/config.json
          strict: false
