name: "License Integrity"
on:
  pull_request:

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-license-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Check License Headers
        # cspell:disable-next-line
        uses: viperproject/check-license-header@v2
        with:
          path: .
          config: ./.github/license-headers/config.json
          strict: false
