# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital and contributors
# SPDX-License-Identifier: MIT

name: Open Source Checks
on:
  pull_request:
  push:
    branches:
      - main

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  check-opensource-scaffold:
    name: Check Opensource Scaffold
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check Opensource Scaffold
        if: github.event_name != 'pull_request'
        uses: ./

  check-license-compliance:
    name: Check License Compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}

      - name: Check License Compliance
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-license-compliance@v0.1.0
        with:
          config-file: .github/check-license-compliance.config.yml

      - name: Check License Compliance
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-license-compliance/.github/actions/check-and-comment@v0.1.0
        with:
          config-file: .github/check-license-compliance.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-spdx-headers:
    name: Check SPDX Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check SPDX Headers
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-spdx-headers@v0.1.0
        with:
          config-file: .github/check-spdx-headers.config.yml

      - name: Check SPDX Headers
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-spdx-headers/.github/actions/check-and-comment@v0.1.0
        with:
          config-file: .github/check-spdx-headers.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
