# SPDX-FileCopyrightText: 2025 Telefonica
# SPDX-License-Identifier: MIT

name: Open Source Checks
on:
  pull_request:
  push:
    branches:
      - main

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  check-opensource-scaffold:
    name: Check Opensource Scaffold
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check Opensource Scaffold
        if: github.event_name != 'pull_request'
        # TODO: Change the template to use the real path once published
        uses: Telefonica/cross-opensource-template/@feat/cli-generator

  check-license-compliance:
    name: Check License Compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # TODO: Add step to install dependencies here

      - name: Check License Compliance
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-license-compliance@v0.1.0
        with:
          config-file: .github/check-license-compliance.config.yml

      - name: Check License Compliance
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-license-compliance/.github/actions/check-and-comment@v0.1.0
        with:
          config-file: .github/check-license-compliance.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-spdx-headers:
    name: Check SPDX Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Check SPDX Headers
        if: github.event_name != 'pull_request'
        uses: Telefonica/check-spdx-headers@v0.1.0
        with:
          config-file: .github/check-spdx-headers.config.yml

      - name: Check SPDX Headers
        if: github.event_name == 'pull_request'
        uses: Telefonica/check-spdx-headers/.github/actions/check-and-comment@v0.1.0
        with:
          config-file: .github/check-spdx-headers.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
